### ISSUE TITLE
Cann't find target .so file under /linux/aarch64 folder, cause exception throw

### ISSUE THREAD

**Issue by jordanhgl** [luben/zstd-jni#32]
hi  luben, I try to use zest-jni (1.1.4) lib in my android project in Android studio IDE, so I import this lib with gradle like:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    testCompile 'junit:junit:4.12'
    compile 'com.github.luben:zstd-jni:1.1.4'
} 
then I build my project and I can find this lib under external Libraries , I can import Zstd.java in my test java class file, here is my test code:

==================

String testJson = "{\"name\":\"line_location\", \"location\":\"1231231231231231231231231231231323123123\"}";
                byte[] encoded = com.github.luben.zstd.Zstd.compress(testJson.getBytes());
                Log.d(tag, "in onClick encoded result is " + encoded);

===================
but when I run my app , this test code catch exception as shown below:

Caused by: java.lang.UnsupportedOperationException: Unsupported OS/arch, cannot find /linux/aarch64/libzstd.so. Please try building from source.
                                                                       at com.github.luben.zstd.util.Native.load(Native.java:55)
                                                                       at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:11)
                                                                       at com.example.hangl.zstdtest.ZstdTestActivity.onClick(ZstdTestActivity.java:68) 
                                                                       at android.view.View.performClick(View.java:5212) 
                                                                       at android.view.View$PerformClick.run(View.java:21214) 
                                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5628) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 

It seems like getResourceAsStream() in Native.java return null obj, then expiation throws, what's the problem with this?

**Comment by luben** [comment]
Hi,

I am not sure exactly what is the problem. I will take a closer look but the linux/aarch64 .so is already in the released jar. See below.

It should be something with paths and streams on Android - I have never tested it there, just on regular aarch64 linux with the oracle JDK.
.
├── aix
│   └── ppc64
│       └── libzstd.so
├── com
│   └── github
│       └── luben
│           └── zstd
│               ├── util
│               │   └── Native.class
│               ├── Zstd.class
│               ├── ZstdDictCompress.class
│               ├── ZstdDictDecompress.class
│               ├── ZstdDirectBufferCompressingStream.class
│               ├── ZstdDirectBufferDecompressingStream.class
│               ├── ZstdInputStream.class
│               └── ZstdOutputStream.class
├── darwin
│   └── x86_64
│       └── libzstd.dylib
├── include
│   ├── com_github_luben_zstd_ZstdDictCompress.h
│   ├── com_github_luben_zstd_ZstdDictDecompress.h
│   ├── com_github_luben_zstd_ZstdDirectBufferCompressingStream.h
│   ├── com_github_luben_zstd_ZstdDirectBufferDecompressingStream.h
│   ├── com_github_luben_zstd_Zstd.h
│   ├── com_github_luben_zstd_ZstdInputStream.h
│   └── com_github_luben_zstd_ZstdOutputStream.h
├── linux
│   ├── aarch64
│   │   └── libzstd.so
│   ├── amd64
│   │   └── libzstd.so
│   ├── i386
│   │   └── libzstd.so
│   └── ppc64
│       └── libzstd.so
├── META-INF
│   └── MANIFEST.MF
├── win
│   ├── amd64
│   │   └── libzstd.dll
│   └── x86
│       └── libzstd.dll

**Comment by luben** [comment]
Hi,

I am not sure exactly what is the problem. I will take a closer look but the linux/aarch64 .so is already in the released jar. See below.

It should be something with paths and streams on Android - I have never tested it there, just on regular aarch64 linux with the oracle JDK.
.
├── aix
│   └── ppc64
│       └── libzstd.so
├── com
│   └── github
│       └── luben
│           └── zstd
│               ├── util
│               │   └── Native.class
│               ├── Zstd.class
│               ├── ZstdDictCompress.class
│               ├── ZstdDictDecompress.class
│               ├── ZstdDirectBufferCompressingStream.class
│               ├── ZstdDirectBufferDecompressingStream.class
│               ├── ZstdInputStream.class
│               └── ZstdOutputStream.class
├── darwin
│   └── x86_64
│       └── libzstd.dylib
├── include
│   ├── com_github_luben_zstd_ZstdDictCompress.h
│   ├── com_github_luben_zstd_ZstdDictDecompress.h
│   ├── com_github_luben_zstd_ZstdDirectBufferCompressingStream.h
│   ├── com_github_luben_zstd_ZstdDirectBufferDecompressingStream.h
│   ├── com_github_luben_zstd_Zstd.h
│   ├── com_github_luben_zstd_ZstdInputStream.h
│   └── com_github_luben_zstd_ZstdOutputStream.h
├── linux
│   ├── aarch64
│   │   └── libzstd.so
│   ├── amd64
│   │   └── libzstd.so
│   ├── i386
│   │   └── libzstd.so
│   └── ppc64
│       └── libzstd.so
├── META-INF
│   └── MANIFEST.MF
├── win
│   ├── amd64
│   │   └── libzstd.dll
│   └── x86
│       └── libzstd.dll

**Comment by luben** [comment]
Looks like it is common problem on Android as getResourceAsStream is not working like on other platforms. Do you know how it could be accomplished?

**Comment by luben** [comment]
@jordanhgl , I pushed a version that loads the shared native library with a relative path. It will hit maven central in 3-4 hours. Can you try it if it solves the problem.

Note, it's the same version 1.1.4 so you will need to manually remove it from your local cache.

**Comment by jordanhgl** [comment]
@luben  thanks for your answer,  I agree with you It's a common problem on Android when use getResourceAsStream，I will test your latest version shared native library and note you the result here.

**Comment by luben** [comment]
@jordanhgl It should solve only part of the problem. The reference to the standard libc.so will still be present. I think we need to have a separate build for Android. It's already a know problem #10 but I have no experience building for Android. Any help is appreciated.

**Comment by jordanhgl** [comment]
@luben   yes I've test your latest lib and It's still not work ,  same exception throw out:
 Caused by: java.lang.UnsupportedOperationException: Unsupported OS/arch, cannot find /linux/aarch64/libzstd.so. Please try building from source.
                                                                             at com.github.luben.zstd.util.Native.load(Native.java:55)
                                                                             at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:11)

I can supply an simple android project with very simple jni use(actually I have no experience how to programe with c\c++ and build shared native lib), 
different .so file should be build by separetely for different cpu arch in android, like armeabi, armeabi-v7i, x86, the project structure  will look like :

project
	|
	|
	|--app(project module)
		|
		|--src
			|
			|--main
				|
				|--java (java code dir)
				|	|
				|	|--yourpackage
				|		|
				|		|--TestZstdActivity.java(main activity for android project you can add your test code in it's onResume())
				|				
				|
				|--jniLibs(where your so file should be put)
				|	|
				|	|--armeabi
				|	|	|
				|	|	|--libzstd.so
				|	|
				|	|--armeabi-v7a
				|	|	|
				|	|	|--libzstd.so
				|	|
				|	|--x86
				|		|
				|		|--libzstd.so
				|
				|--res(android resource folder with pics and layouts)
		
	|
	|
	|
	|
	|
	|--build.gradle
	|
	|
	|
	|

after build shared native lib for different cpu arch, then put them into target folder under jniLibs/, then your can load target .so with System.loadLibrary("zstd") in android, if they can't be loaded add sourceSets config to your build.gradle which under app module dir like this,

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.example.hangl"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    //add this to locate shared native lib 
    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}


 if You can supply an email I will send you the demo project(my github use email is jordanhgl@gmail.com), if your want run the project you need to install a lastest version Android studio IDE (My studio is 2.2.1), then simple import my demo project by File->open->build.gralde under target project, if you run it, you will need to connect an android phone to your computer via a usb line. if it's not conveniently to do this, can you help to build some .so file for different cpu arch(armeabi, armeabi-v7a and x86 mainly)? and I will make a test and tell you the result, Our team very much hope to use zstd in our project. Thanks for your help.

**Comment by luben** [comment]
yes. I will write you about the demo project. In the other issue comment you said that you made it load the .so file but failed because the libc linking issues. Do you have example how you construct the resource path as I think this is different on android, so that we can try it also if the default fails.

**Comment by jordanhgl** [comment]
@luben   I try to build your source file under native/ in Android studio IDE, Android studio with NDK build tools installed can build c/c++ source files and create shared native library for different ABI, now I'm learning how to use ndk build, If I success I will show you my demo project in my git repo. if the issues you mentioned about libc linking still exist I will contact you here, Thank your.

**Comment by jordanhgl** [comment]
@luben I've successfully built native shared libraries for zstd use on Android, here is my demo [project](https://github.com/jordanhgl/zstd_4_android), and I reply your email some question in my email, hope you can do me a favor, Thanks.

**Comment by luben** [comment]
@jordanhgl, I think I made it work on android. See the last commits.

**Comment by luben** [comment]
If you have suggestions about the distribution model, please give and advice in #54
